#!/usr/bin/env bash
set -euo pipefail

# ── Constants ─────────────────────────────────────────────────────────────────
REPO_URL="https://github.com/fariebee/forge-deploy"
INSTALL_DIR="/opt/forge"

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${GREEN}▸${NC} $*"; }
warn()    { echo -e "${YELLOW}⚠${NC}  $*"; }
error()   { echo -e "${RED}✗${NC}  $*" >&2; }
bold()    { echo -e "${BOLD}$*${NC}"; }
die()     { error "$*"; exit 1; }

# ── Preflight ─────────────────────────────────────────────────────────────────
preflight() {
    [[ "$EUID" -eq 0 ]] || die "This script must be run as root (try: sudo bash $0)"

    if [[ -f /etc/os-release ]]; then
        # shellcheck source=/dev/null
        source /etc/os-release
        [[ "$ID" == "ubuntu" || "$ID" == "debian" || "${ID_LIKE:-}" == *"debian"* ]] \
            || die "Unsupported OS: $PRETTY_NAME. Only Ubuntu/Debian are supported."
    else
        die "Cannot detect OS — /etc/os-release not found."
    fi

    info "Preflight passed ($PRETTY_NAME)"
}

# ── Dependency installation ───────────────────────────────────────────────────
install_docker() {
    if command -v docker &>/dev/null; then
        info "Docker already installed ($(docker --version | cut -d' ' -f3 | tr -d ','))"
        return
    fi

    info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
    info "Docker installed"
}

install_deps() {
    install_docker
}

# ── Config prompts ────────────────────────────────────────────────────────────
prompt_config() {
    echo ""
    bold "Configure your Forge installation:"
    echo ""

    while true; do
        read -rp "  Domain (e.g. forge.example.com): " DOMAIN
        [[ -n "$DOMAIN" ]] && break
        warn "Domain cannot be empty"
    done

    while true; do
        read -rsp "  Admin password: " ADMIN_PASSWORD
        echo ""
        [[ -n "$ADMIN_PASSWORD" ]] && break
        warn "Admin password cannot be empty"
    done

    echo "  GoDaddy API token — create at https://developer.godaddy.com/keys"
    echo "  Format: <API_KEY>:<API_SECRET>"
    while true; do
        read -rsp "  GoDaddy API token: " GODADDY_API_TOKEN
        echo ""
        [[ -n "$GODADDY_API_TOKEN" ]] && break
        warn "GoDaddy API token cannot be empty"
    done

    echo ""
    info "Configuration collected"

    export DOMAIN ADMIN_PASSWORD GODADDY_API_TOKEN
}

# ── .env generation ───────────────────────────────────────────────────────────
generate_and_write_env() {
    if [[ -f "$INSTALL_DIR/.env" ]]; then
        die ".env already exists at $INSTALL_DIR/.env — refusing to overwrite existing secrets. If this is intentional, remove the file and re-run."
    fi

    info "Generating secrets..."

    local pg_pass jwt_secret redis_pass minio_pass secrets_key docker_gid searxng_api_key searxng_secret_key
    local rag_pg_pass

    pg_pass=$(openssl rand -hex 32)
    jwt_secret=$(openssl rand -base64 32)
    # Redis password must be URL-safe — it's embedded in redis:// URLs unescaped,
    # and base64's `/`, `+`, `=` break url.Parse on the Go side.
    redis_pass=$(openssl rand -hex 32)
    minio_pass=$(openssl rand -base64 32)
    secrets_key=$(openssl rand -hex 32)
    docker_gid=$(getent group docker | cut -d: -f3)
    searxng_api_key=$(openssl rand -hex 32)
    searxng_secret_key=$(openssl rand -hex 32)
    rag_pg_pass=$(openssl rand -hex 24)
    forge_app_db_pass=$(openssl rand -hex 24)

    info "Writing .env to $INSTALL_DIR/.env"

    cat > "$INSTALL_DIR/.env" <<EOF
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT — contains secrets

DOMAIN=$DOMAIN

ADMIN_PASSWORD=$ADMIN_PASSWORD

JWT_SECRET=$jwt_secret

SECRETS_KEY=$secrets_key

POSTGRES_SUPERUSER_PASSWORD=$pg_pass
MASTER_PG_URL=postgresql://postgres:${pg_pass}@localhost:5432/postgres

PUBLIC_PG_HOST=$DOMAIN
PUBLIC_PG_PORT=6432
PUBLIC_PG_DIRECT_PORT=5432

REDIS_PASSWORD=$redis_pass
PUBLIC_REDIS_HOST=$DOMAIN
PUBLIC_REDIS_PORT=6379

MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=$minio_pass
PUBLIC_MINIO_HOST=s3.$DOMAIN

CADDY_ADMIN_URL=http://caddy:2019
PGFORGE_NETWORK=pgforge-net
BIND_HOST=127.0.0.1
DOCKER_GID=$docker_gid

REGISTRY_URL=registry.$DOMAIN

GODADDY_API_TOKEN=$GODADDY_API_TOKEN

# Multitenancy RLS backstop: password for the non-superuser `forge_app` Postgres
# role. Forge serves read requests through it so the row-level-security
# org_isolation policies actually apply (the main pool is a superuser and
# bypasses FORCE RLS). The role is created/updated automatically at startup.
# Leave empty to disable the backstop — org isolation then rests solely on
# application-layer filtering.
FORGE_APP_DB_PASSWORD=$forge_app_db_pass

# SearxNG — set COMPOSE_PROFILES=searxng below to enable.
SEARXNG_API_KEY=$searxng_api_key
SEARXNG_SECRET_KEY=$searxng_secret_key

# RAG — set COMPOSE_PROFILES=rag below to enable. RAG_GATEWAY_TOKEN must be
# set manually to a pgl_* token issued from the LLM gateway page; embedding
# calls use it so usage shows up under "rag" rather than under an app.
RAG_PG_PASSWORD=$rag_pg_pass
RAG_PG_URL=postgres://forge:${rag_pg_pass}@forge-rag-pg:5432/rag?sslmode=disable
RAG_GATEWAY_TOKEN=
RAG_WORKER_CONCURRENCY=2
RAG_MAX_PDF_BYTES=104857600
EOF

    export POSTGRES_SUPERUSER_PASSWORD="$pg_pass"
    chmod 600 "$INSTALL_DIR/.env"
    info ".env written (mode 600)"
}

# ── Repo + services ───────────────────────────────────────────────────────────
clone_repo() {
    if [[ -d "$INSTALL_DIR/.git" ]]; then
        info "Repo already cloned at $INSTALL_DIR"
        return
    fi
    info "Cloning Forge repository..."
    # Ubuntu 24.04 ships libcurl 8.5, whose HTTP/2 handling makes anonymous
    # clones from github.com fail intermittently with "could not read Username"
    # (401 on the upload-pack POST). HTTP/1.1 is reliable.
    git -c http.version=HTTP/1.1 clone "$REPO_URL" "$INSTALL_DIR"
    info "Repository cloned"
}

start_services() {
    # deploy.sh itself runs via `curl | bash`, so $0 isn't a path into the
    # cloned repo — reach the preflight check via INSTALL_DIR instead.
    "$INSTALL_DIR/scripts/preflight-objectstore.sh"

    info "Pulling latest images..."
    docker compose -f "$INSTALL_DIR/docker-compose.yml" \
        --env-file "$INSTALL_DIR/.env" pull

    info "Starting services..."
    docker compose -f "$INSTALL_DIR/docker-compose.yml" \
        --env-file "$INSTALL_DIR/.env" up -d

    info "Services started"
}

wait_for_postgres() {
    info "Waiting for Postgres to be ready..."
    local attempts=30
    for _ in $(seq 1 "$attempts"); do
        if docker exec pgforge-postgres pg_isready -U postgres &>/dev/null; then
            info "Postgres is ready"
            return 0
        fi
        sleep 1
    done
    die "Postgres did not become healthy within ${attempts}s — check: docker logs pgforge-postgres"
}

# ── Summary ───────────────────────────────────────────────────────────────────
print_summary() {
    local domain="$1"
    echo ""
    bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bold "  Forge installed successfully!"
    bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo -e "  URL:            ${GREEN}https://$domain${NC}"
    echo -e "  Admin password: (the password you entered)"
    echo ""
    warn "Save your .env — it contains generated secrets:"
    echo "     $INSTALL_DIR/.env"
    bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
}

# ── Install / update flows ────────────────────────────────────────────────────
fresh_install() {
    prompt_config
    clone_repo
    generate_and_write_env
    start_services
    wait_for_postgres
    install_host_cli
    print_summary "$DOMAIN" "$ADMIN_PASSWORD"
}

do_update() {
    info "Updating Forge..."

    info "Pulling latest code..."
    git -C "$INSTALL_DIR" pull

    start_services
    wait_for_postgres
    install_host_cli

    local version
    version=$(git -C "$INSTALL_DIR" describe --tags --always 2>/dev/null || echo "latest")
    echo ""
    bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bold "  Forge updated to $version"
    bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
}

# install_host_cli pulls the `pgforge` binary out of the running app container
# so the operator's host CLI always matches the deployed server version.
# Non-fatal: if the container isn't up yet the user can run it later.
install_host_cli() {
    if [[ -x "$INSTALL_DIR/scripts/install-pgforge.sh" ]]; then
        info "Installing host pgforge CLI..."
        if bash "$INSTALL_DIR/scripts/install-pgforge.sh" 2>&1 | sed 's/^/    /'; then
            info "pgforge CLI installed"
        else
            warn "pgforge CLI install skipped (run later: bash $INSTALL_DIR/scripts/install-pgforge.sh)"
        fi
    fi
}

# ── Mode detection ────────────────────────────────────────────────────────────
is_installed() {
    [[ -f "$INSTALL_DIR/.env" ]] && \
    docker ps --filter "name=pgforge-app" --filter "status=running" \
              --format "{{.Names}}" 2>/dev/null | grep -q pgforge-app
}

# ── Entry point ───────────────────────────────────────────────────────────────
main() {
    bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bold "  Forge Deploy Script"
    bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    preflight
    install_deps

    if is_installed; then
        do_update
    else
        fresh_install
    fi
}

main "$@"
